-- MySQL Script generated by MySQL Workbench
-- Sun Nov 29 21:36:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema scooter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scooter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scooter` DEFAULT CHARACTER SET utf8 ;
USE `scooter` ;

-- -----------------------------------------------------
-- Table `scooter`.`vehicle_models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scooter`.`vehicle_models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `scooter`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scooter`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(57) NULL,
  `district` VARCHAR(255) NULL,
  `street` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scooter`.`rental_offices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scooter`.`rental_offices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `location_id` INT NOT NULL,
  `latitude` DECIMAL(8,6) NOT NULL,
  `longtitude` DECIMAL(8,6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_rental_offices_locations1_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_rental_offices_locations1`
    FOREIGN KEY (`location_id`)
    REFERENCES `scooter`.`locations` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scooter`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scooter`.`vehicles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vehicle_model_id` INT NOT NULL,
  `current_rental_office_id` INT NULL,
  `registration_number` VARCHAR(45) NULL,
  `registration_date` DATE NULL,
  `charge_level` INT NULL,
  `technical_condition_level` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bikes_bike_models1_idx` (`vehicle_model_id` ASC) VISIBLE,
  INDEX `fk_vehicles_rental_points1_idx` (`current_rental_office_id` ASC) VISIBLE,
  CONSTRAINT `fk_bikes_bike_models1`
    FOREIGN KEY (`vehicle_model_id`)
    REFERENCES `scooter`.`vehicle_models` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_vehicles_rental_points1`
    FOREIGN KEY (`current_rental_office_id`)
    REFERENCES `scooter`.`rental_offices` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scooter`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scooter`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NULL,
  `password` VARCHAR(100) NULL,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scooter`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scooter`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scooter`.`users_to_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scooter`.`users_to_roles` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_to_role_roles1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_to_role_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `scooter`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_to_role_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `scooter`.`roles` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scooter`.`tariffs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scooter`.`tariffs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `timely_price` DECIMAL(6,2) ZEROFILL NULL,
  `per_unit_time` INT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scooter`.`discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scooter`.`discounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `discount_percentage` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scooter`.`rentals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scooter`.`rentals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `vehicle_id` INT NULL,
  `status` INT NOT NULL COMMENT '0 - IN PROGRESS\n1 - DONE\n2 - CANCELED',
  `start_rental_date_time` DATETIME NOT NULL,
  `start_rental_office_id` INT NULL,
  `tariff_id` INT NOT NULL,
  `discount_id` INT NULL DEFAULT NULL,
  `finish_rental_date_time` DATETIME NULL DEFAULT NULL,
  `finish_rental_office_id` INT NULL DEFAULT NULL,
  `discount_amount` DECIMAL(6,2) NULL DEFAULT NULL,
  `total_cost` DECIMAL(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rents_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_rents_bikes1_idx` (`vehicle_id` ASC) VISIBLE,
  INDEX `fk_rentals_tariffs1_idx` (`tariff_id` ASC) VISIBLE,
  INDEX `fk_rentals_rental_points1_idx` (`start_rental_office_id` ASC) VISIBLE,
  INDEX `fk_rentals_finish_rental_points_idx` (`finish_rental_office_id` ASC) VISIBLE,
  INDEX `fk_rentals_discounts1_idx` (`discount_id` ASC) VISIBLE,
  CONSTRAINT `fk_rents_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `scooter`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rental_vehicles`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `scooter`.`vehicles` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rentals_tariffs`
    FOREIGN KEY (`tariff_id`)
    REFERENCES `scooter`.`tariffs` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rentals_start_rental_points`
    FOREIGN KEY (`start_rental_office_id`)
    REFERENCES `scooter`.`rental_offices` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rentals_finish_rental_points`
    FOREIGN KEY (`finish_rental_office_id`)
    REFERENCES `scooter`.`rental_offices` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rentals_discounts1`
    FOREIGN KEY (`discount_id`)
    REFERENCES `scooter`.`discounts` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scooter`.`expired_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scooter`.`expired_tokens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
